---

# MUNIN
munin_htmldir: /var/cache/munin/www

munin_node_plugins:
  - name: uptime

# configure per inventory
# munin_admin_user: munin
# munin_admin_password: munin
# munin_alerts: []

# SERVER
server_monit_load_memory: 90%
