---

# MUNIN
munin_htmldir: /var/cache/munin/www

deploy_ansible_version: "2.1.3.0"

munin_packages:
  - python-passlib
  - munin
  - munin-plugins-extra

# settings to configure per inventory
# munin_admin_user: munin
# munin_admin_password: munin
# munin_alerts: []
# munin_node_plugins: []

# SERVER
server_monit_load_memory: 90%
