---

- name: check ansible version
  hosts: localhost
  become: no
  connection: local

  vars:
    testing: false

  tasks:

- name: visit master (facts)
  hosts: master
  user: "{{ deploy_user }}"
  become: yes

- name: visit node (facts)
  hosts: node
  user: "{{ deploy_user }}"
  become: yes
